% Formats a plot in a standard way
set( gca                  , ...
    'FontName'   , 'Arial', ...
    'FontSize'   , 10 );
set( [hXLabel, hYLabel], ...
    'FontName'   , 'Arial');

if exist('hLegend','var')
    set([hLegend, gca]     , ...
    'FontSize'   , 10           );
end

set(gca, ...
  'Box'         , 'on'      , ...
  'TickDir'     , 'in'      , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'LineWidth'   , 1         );

if exist('hData','var')
    
    for i = 1:length(hData)
        if iscell(hData)
            d = hData{i};
        else
            d = hData;
        end
        set(d                      , ...
        'Marker'          , 'none'         , ...
        'MarkerSize'      , 1           , ...
        'MarkerEdgeColor' , 'black'      , ...
        'LineWidth'       , 2           , ...
        'MarkerFaceColor' , [.75 .75 1] );
    end
end

if exist('hE','var')
    set(hE                            , ...
      'LineStyle'       , 'none'      , ...
      'Marker'          , '.'         , ...
      'Color'           , [.3 .3 .3]  , ...
      'LineWidth'       , 3           , ...
      'Marker'          , 'o'         , ...
      'MarkerSize'      , 1           , ...
      'MarkerEdgeColor' , [.2 .2 .2]  , ...
      'MarkerFaceColor' , [.7 .7 .7]  );
end

if exist('hFit','var')
    set(hFit                          , ...
      'LineStyle'       , '-'         , ...
      'LineWidth'       , 2           , ...
      'Color'           , 'black'     );
end